# Generated by Django 4.0 on 2021-12-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(verbose_name='вместимость')),
                ('is_free', models.BooleanField(default=True, verbose_name='свободен')),
                ('url', models.CharField(max_length=64, verbose_name='ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='TableInfo',
            fields=[
                ('table_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.table')),
                ('name', models.CharField(max_length=32, verbose_name='имя столика')),
                ('info', models.TextField(verbose_name='описание столика')),
                ('photo', models.ImageField(upload_to='restaurant/tables/')),
            ],
        ),
    ]
